# ╭─────────────────────────────────ImplementationGuide-fish.json──────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see:                                                                    │
# │  https://fshschool.org/docs/sushi/configuration/#full-configuration                            │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: silth.fhir.th.palliative
canonical: https://fhir-ig.sil-th.org/th-palliative
version: 0.1.0-preview
name: THPalliative
title: (draft) TH Palliative Care - FHIR Implementation Guide
status: draft
publisher:
  name: Standards and Interoperability Lab - Thailand (SIL-TH)
# contact:
#   - name: Bill Cod
#     telecom:
#       - system: email
#         value: cod@reef.gov
# jurisdiction: "urn:iso:std:iso:3166#TH"
description: An IG for communicating with the FHIR API.
license: CC0-1.0
fhirVersion: 5.0.0
dependencies:
  silth.fhir.terminology.core: 0.1.2
  silth.fhir.th.extensions: 1.0.0
  silth.fhir.th.core: dev
  hl7.fhir.uv.ips: 1.1.0
parameters:
  apply-publisher: true
  apply-contact: true
  show-inherited-invariants: false
  excludettl: true
  excludemap: true
copyrightYear: 2023+
releaseLabel: qa-preview

pages:
  index.md:
    title: TH Palliative Care FHIR IG
  profiles.md:
    title: รายการ Profiles
  change_log.md:
    title: Release Notes
  general-guidance.md:
    title: คำแนะนำทั่วไป

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  หน้าแรก: index.html
  สารบัญ: toc.html
  คำแนะนำ:
    คำแนะนำทั่วไป: general-guidance.html
  เนื้อหาทั้งหมด: artifacts.html
  Profiles: profiles.html
  อื่น ๆ:
    Release Notes: change_log.html
